feat: add `ark update readme` command
alexellis/arkade pull request #1139
Opened 2024-11-20 21:00 UTC by rgee0

## Description

Adds a subcommand to update that will update the README tables in situ. This will be useful to contributors who are adding system installs / apps / tools as it will remove the need for the existing manual mechanism to update the appropriate tables in the readme.  Running `arkade update readme` will update each of the three tables in the readme, ready to be committed with their change.

## Motivation and Context
- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))
Discussed on the community call

## How Has This Been Tested?

### Functional
```
➜  arkade git:(updateReadmeTables) ✗ ./arkade update readme
Updated system table.
Updated apps table.
Updated tools table.
README tables updated successfully
```
README shows new format as per commit included in this change

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [x ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

2025-02-28 15:42 UTC, alexellis commented on cmd/update/readme.go
> +to quickly create a Cobra application.`,
Could you include the supported markers in the Cobra help message please?

2025-02-28 15:42 UTC, alexellis requested changes
I think this looks good.. I'm asking for a bit more in the go-docs first

2025-02-28 15:45 UTC, rgee0 commented on cmd/update/readme.go
> +to quickly create a Cobra application.`,
Yes.  Quite the oversight 😆

2025-03-01 08:05 UTC, rgee0 commented on cmd/update/readme.go
> +to quickly create a Cobra application.`,
Added some detail here

2025-03-01 08:23 UTC, rgee0 commented
We should probably update the PR template once this goes in, as well as the trailing note in the README

2025-03-23 07:11 UTC, rgee0 commented
Resolved the conflicts in the `readme` this morning

2025-11-14 21:39 UTC, closed without merging