Add Metallb app for install
alexellis/arkade pull request #329
Opened 2021-02-03 23:16 UTC by networkop

## Description
This PR adds support for metallb installation. It installs metallb in [L2 mode](https://metallb.universe.tf/concepts/layer2/) and provides an argument for configurable LB IP range (default: 192.168.0.0/24)

## Motivation and Context
Fixes #76 
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

**Notes**:
* It uses the [official](https://metallb.universe.tf/installation/) installation method, it doesn't rely on 3rd party helm charts (e.g. [bitnami](https://bitnami.com/stack/metallb/helm))
* It adds a new function [`KubectlIn`](https://github.com/alexellis/arkade/compare/master...networkop:master#diff-53f55403dea3cbf51eac6f9161c38f774e6e21d86f0d4af6afbb49d9d3468077R68) to allow YAML manifests to be passed via stdin  

## How Has This Been Tested?

Deploy to a new cluster:
```
./arkade install metallb --address-range 172.16.0.0/24
```

Any pending loadBalancer services will soon get a new IP:
```
k get svc -A
NAMESPACE              NAME                                 TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
default                ingress-nginx-controller             LoadBalancer   10.108.196.250   172.16.0.0   80:30611/TCP,443:32517/TCP   68s
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

2021-06-01 13:43 UTC, alexellis commented
Does it make sense to only install in L2 mode?

What other modes are available and would be typically required?

I understand that Kinvolk maintain parts of metallb, so I'm going to ping @vbatts to see if he can shoulder tap someone.

Alex

2021-06-01 14:15 UTC, vbatts commented
cc @rata @johananl @russellb

2021-06-01 14:18 UTC, networkop commented
The other alternative is the L3/BGP mode which requires a lot more input from a user and at least one BGP speaker, so (based on my understanding) it's not really compatible with arkade's easy to get started approach. 

L2 mode, otoh can work out of the box on any Linux distro with minimum dependencies.

2021-08-05 09:54 UTC, alexellis commented on cmd/apps/metallb_app.go
> +			return fmt.Errorf("Create secret error: %+v", err)
Go errors should start with a lowercase letter

2021-08-05 09:54 UTC, alexellis commented on cmd/apps/metallb_app.go
> +		addressRange, _ := command.Flags().GetString("address-range")
Validate this flag by adding a PreRunE handler, you'll see how in the other apps.

2021-08-05 09:55 UTC, alexellis commented on cmd/apps/metallb_app.go
> +		Long:         `Install metallb for service type:LoadBalancer`,
This is taken from the GitHub repo and is more descriptive:

`Install a network load-balancer implementation for Kubernetes using standard routing protocols`

2021-08-05 09:55 UTC, alexellis commented on cmd/apps/metallb_app.go
> +		Example:      `arkade install metallb`,
Provide an example with an overridden CIDR please

2021-08-05 09:56 UTC, alexellis commented on cmd/apps/metallb_app.go
> +		token := make([]byte, 32)
This should probably be overridden by an optional flag, so users can automate and use a known key.

2021-08-05 09:56 UTC, alexellis commented on cmd/apps/metallb_app.go
> +		err = k8s.CreateSecret(secret)
Can you inline this?

```
if err := ... ; err != nil {
    return ....
}
```

2021-08-05 09:56 UTC, alexellis commented on cmd/apps/metallb_app.go
> +		err = k8s.KubectlIn(strings.NewReader(configMap), "apply", "-f", "-")
Please also inline this error

2021-08-05 09:57 UTC, alexellis commented on cmd/apps/metallb_app.go
> +# https://metallb.universe.tf/
You are generating a token, but then don't give the user instructions on how to source or view that token.

A command might help here?

I'd also suggest that you give a command to show them the metallb config map that was generated and applied.

2021-08-05 09:58 UTC, alexellis requested changes
Adding review comments, please also update the list of apps in the README by running `arkade get --help`

2021-08-05 09:58 UTC, alexellis commented
This requires a rebase, an update to the README, and there are some review comments.

I'd like you to add a note that this is only for ARP mode, so that users do not require BGP, i.e. Equinix Metal customers.

Maybe call the app metallb-arp?

2021-09-15 09:08 UTC, closed without merging

2021-09-15 09:08 UTC, alexellis commented
Closed via #512