Use text/template instead of html/template for binary url
alexellis/arkade pull request #447
Opened 2021-07-06 14:35 UTC by soider

Signed-off-by: Mikhail Sakhnov <msakhnov@mirantis.com>

## Description
The html/template claims to be template renderer engine which outputs html
It sanitizes outputs the same way as html by adding escaping

That breaks final URL if version or tool name or any other used field has different special signs in it

## Motivation and Context
If there are + signs or any other escaping signs in the version or name, the final url is broken.

## How Has This Been Tested?
By running existed test suite and manually downloading few tools

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

2021-07-06 17:05 UTC, alexellis commented
Hi @soider as part of our contributing process, can you raise an issue for this please and give a specific use-case that shows a template failing?

Thanks,

Alex

2021-07-06 17:06 UTC, alexellis commented
In the meantime I'll approve the CI to run.

2021-07-13 11:48 UTC, alexellis commented on pkg/get/tools.go
> +	if runtime.GOOS != "darwin" {
We have code to handle this, so would just remove that if guard.

2021-07-13 11:48 UTC, alexellis requested changes
This is shaping up very nicely. Could you just take a look at the note I left for you and amend that last commit and force push after?

2021-07-13 11:49 UTC, alexellis commented
@yankeexe we have a PR for K0s already here, so we may want to close #454

2021-07-13 11:49 UTC, alexellis commented
@soider please see the error: https://github.com/alexellis/arkade/pull/447/checks?check_run_id=3056341788

2021-07-14 13:51 UTC, alexellis commented
FYI we have a rebase conflict on this now too. Could you fix? https://www.youtube.com/watch?v=8j0H6urZ-bU

2021-07-20 09:59 UTC, soider commented
I resolved the conflict and dropped the check for darwin OS

2021-07-20 10:05 UTC, soider commented
@alexellis as I mentioned, I dropped the OS check in the tools list, though I still able to download binary on darwin (while the binary doesn't support darwin)

2021-07-21 18:16 UTC, alexellis commented
We have another rebase issue, sorry about that - due to merging #457 

Once resolved, I'll merge this and then make a recommendation about Darwin. We can detect the OS during the string building template, so that might be a good place to add extra text that would make it fail to match a valid binary.

2021-07-21 19:26 UTC, soider commented
@alexellis rebased on master branch

2021-07-21 20:12 UTC, merged

2021-07-21 20:12 UTC, alexellis commented
Merged, thank you for the patience.

2021-07-22 12:08 UTC, soider commented
@alexellis and thank you for the hints as well!

2021-07-22 12:09 UTC, alexellis commented
Want to try that suffix that's normally empty but breaks the URL delicately for Darwin?

2021-07-22 12:12 UTC, soider commented
@alexellis I am not sure I understand what are you about. Could you explain a little further?

2021-07-22 12:15 UTC, alexellis commented
Didn't you tell me that k0s downloads in error on Darwin?

Break its URL on purpose so that it gives the error saying that it's unavailable.

2021-07-22 12:17 UTC, soider commented
Oh, yeah, got you. Good point actually, if the k0s changed the url scheme, I'd re-iterate the changes introduced here.