feat: add kube-prometheus-stack
alexellis/arkade pull request #561
Opened 2021-10-23 13:54 UTC by cpanato

## Description
add kube-prometheus-stack that can deploy the prometheus operator / prometheus stack

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Fixes https://github.com/alexellis/arkade/issues/4

## How Has This Been Tested?

## Are you a GitHub Sponsor (Yes/No?)

- [x] Yes
- [ ] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

output of the installation in my raspi home cluster

```
$ ./arkade install kube-prometheus-stack --alertmanager=false --node-exporter=false --kube-state-metrics=false --namespace monitoring --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues="false"

2021/10/23 15:37:05
Using Kubeconfig: /Users/cpanato/Documents/k3s_config
[Warning] unable to create namespace monitoring, may already exist: Error from server (AlreadyExists): namespaces "monitoring" already exists
Client: x86_64, Darwin
2021/10/23 15:37:05 User dir established as: /Users/cpanato/.arkade/
"prometheus-community" already exists with the same configuration, skipping

VALUES values.yaml
Command: /Users/cpanato/.arkade/bin/helm [upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --values /var/folders/cz/_mkxxyx97n38b5p0hs3n2j2m0000gn/T/charts/kube-prometheus-stack/values.yaml --set nodeExporter.enabled=false --set kubeStateMetrics.enabled=false --set prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set alertmanager.enabled=false --set grafana.enabled=false]
Release "kube-prometheus-stack" does not exist. Installing it now.
W1023 15:37:10.566770   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:10.593948   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:12.779896   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:14.040563   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:28.990942   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:29.275248   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:29.289183   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:44.752281   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:49.114189   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:38:08.176979   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME: kube-prometheus-stack
LAST DEPLOYED: Sat Oct 23 15:37:10 2021
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace monitoring get pods -l "release=kube-prometheus-stack"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
2021/10/23 15:38:11 stderr: W1023 15:37:10.566770   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:10.593948   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:12.779896   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:14.040563   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:28.990942   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:29.275248   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:29.289183   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:44.752281   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:37:49.114189   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1023 15:38:08.176979   98411 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

=======================================================================
= kube-prometheus-stack has been installed.                           =
=======================================================================

# Get started with kube-prometheus-stack here:
# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.

 # Forward traffic to your localhost for prometheus
 kubectl port-forward service/prometheus-operated 9090:9090

 # Forward traffic to your localhost for alertmanager (if installed)
 kubectl port-forward service/alertmanager-operated 9093:9093

Thanks for using arkade!
```

also tested in a Kind cluster and AWS EKS

2021-11-04 19:14 UTC, alexellis requested changes
Does this work on arm64/armhf?

Could you add a PreRunE to validate all booleans please? See the Istio app for an example of how I did this.

2021-11-05 08:29 UTC, cpanato commented
> Does this work on arm64/armhf?
> 
> Could you add a PreRunE to validate all booleans please? See the Istio app for an example of how I did this.

tested on my raspberry pie cluster and worked fine, I did not test in a arm64 machines, but the image manifests show that is supported

2022-07-01 17:13 UTC, Shikachuu commented
@cpanato can you do a rebase please?

2022-07-21 12:42 UTC, cpanato commented
@Shikachuu done PTAL

2022-07-21 17:21 UTC, Shikachuu commented
> @Shikachuu done PTAL

Thanks!
@alexellis, this one is ready to merge!

2022-08-29 14:41 UTC, alexellis commented
I would like this app, but it may need updating and definitely needs a rebase. @cpanato

2022-09-20 07:32 UTC, cpanato commented
@alexellis @Shikachuu rebased!

2023-02-02 14:28 UTC, Jasstkn commented
@cpanato hey. sorry for the long reply. I was scrolling through the opened PRs and noticed that kube-prometheus-stack is still not in the arkade. Do you want to rebase it from main branch once again and I could take a look then?

2023-02-14 13:59 UTC, cpanato commented
> @cpanato hey. sorry for the long reply. I was scrolling through the opened PRs and noticed that kube-prometheus-stack is still not in the arkade. Do you want to rebase it from main branch once again and I could take a look then?

rebased

2023-02-15 18:16 UTC, Jasstkn requested changes
Hi. Left a few commands, in general I've tested it manually - and it works just fine.

2023-02-15 18:16 UTC, Jasstkn commented on cmd/apps/prometheus_operator_app.go
> +		}
I think update-repo is missing from here.

2023-05-15 11:41 UTC, cpanato commented
I will close this PR, a bit with no time to update and go over all again :/

2023-05-15 11:41 UTC, closed without merging