Update kubeseal template
alexellis/arkade pull request #611
Opened 2022-01-20 00:32 UTC by yankeexe

Signed-off-by: Yankee Maharjan <yankee.exe@gmail.com>

## Description

Closes #603 

`kubeseal` updated their release format: 
- previous: binary
- now: tar.gz

Update the template to get the latest distribution format.

## Motivation and Context

- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```bash
go run . get kubeseal
```

<details>
<summary><strong>Demo</strong></summary>
<img src="https://user-images.githubusercontent.com/13623913/150240275-331c91f8-630f-44a9-bf60-8cc2c345cccf.png" width=900 />
</details>

<details>
<summary><strong>Test on RPi</strong></summary>
<img src="https://user-images.githubusercontent.com/13623913/150240455-9e3a6221-9fd6-4451-bdef-fe7991a79e79.png" width=900 />
</details>

## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [x] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

2022-01-25 16:27 UTC, alexellis commented on pkg/get/tools.go
> +			Version:     "v0.17.2",
We should remove this version so it can be auto-detected. Can you make that change and test again please?

2022-01-25 16:27 UTC, alexellis requested changes
Requesting a change.

2022-01-25 16:41 UTC, yankeexe commented
@alexellis  Updated!

2022-02-12 15:28 UTC, alexellis commented
LGTM @yankeexe 

@Yannig please see how we did this without changing the code of arkade itself.

Let me know if you see any differences in results.

2022-02-12 15:28 UTC, merged