Add fzf to arkade get
alexellis/arkade pull request #669
Opened 2022-04-07 16:27 UTC by Shikachuu

## Description
`fzf` is the most popular fuzzy find cli tool.
Also removed the duplicate kumactl (probably it was a merge leftover)

## Motivation and Context
- [ ] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer ([required](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Covered with unit tests.
`make e2e` passed.
Also tested with the following shell script:
```bash
#!/bin/bash

set -e -x -u -o pipefail

go build 

./arkade get fzf --arch arm64 --os darwin --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch x86_64 --os darwin --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch x86_64 --os linux --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch arm64 --os linux --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch armv7l --os linux --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch armv6l --os linux --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch x86_64 --os ming --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch arm64 --os ming --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch armv7l --os ming --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf

./arkade get fzf --arch armv6l --os ming --quiet
file $HOME/.arkade/bin/fzf
rm $HOME/.arkade/bin/fzf
```
<details>
<summary>Output</summary>
<pre><code>
/home/shika/.arkade/bin/fzf: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
/home/shika/.arkade/bin/fzf: Mach-O 64-bit x86_64 executable
/home/shika/.arkade/bin/fzf: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Ch5o9kNIIvTaJTliKgZU/OlxB46JDJUSZcH4EhslB/QxuQjCvGx9aQ84diXNo8/TueTdrn9ahEos8yXYrO5, stripped
/home/shika/.arkade/bin/fzf: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=0bQ5QBFXILUT1YVkRNWG/AbBnYAaKlkGeVy0EuXHJ/LipobelVZtQeSsE_r43i/QmJ8Knj5qVV4h715FIXc, stripped
/home/shika/.arkade/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=agTZxLrb-xWx_Mfdw71R/L8RGbKA5tmdxzT3v_AjA/6YVr9g0ahV-LhLHh4HbX/rgVRb51x0O5piKg6nOTo, stripped
/home/shika/.arkade/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=wkg1cdYKr9v93uFUvtP1/yoX_fcnAz-EFoqTqnDIV/6YVr9g0ahV-LhLHh4HbX/bko2rZZHk65jKpzPP9ez, stripped
/home/shika/.arkade/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=wkg1cdYKr9v93uFUvtP1/yoX_fcnAz-EFoqTqnDIV/6YVr9g0ahV-LhLHh4HbX/bko2rZZHk65jKpzPP9ez, stripped
/home/shika/.arkade/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=wkg1cdYKr9v93uFUvtP1/yoX_fcnAz-EFoqTqnDIV/6YVr9g0ahV-LhLHh4HbX/bko2rZZHk65jKpzPP9ez, stripped
/home/shika/.arkade/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=wkg1cdYKr9v93uFUvtP1/yoX_fcnAz-EFoqTqnDIV/6YVr9g0ahV-LhLHh4HbX/bko2rZZHk65jKpzPP9ez, stripped
/home/shika/.arkade/bin/fzf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=wkg1cdYKr9v93uFUvtP1/yoX_fcnAz-EFoqTqnDIV/6YVr9g0ahV-LhLHh4HbX/bko2rZZHk65jKpzPP9ez, stripped
</code></pre>
</details>
## Are you a GitHub Sponsor (Yes/No?)

- [ ] Yes
- [X] No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [X] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

- [X] I have tested this on arm, or have added code to prevent deployment

2022-04-07 17:39 UTC, alexellis commented
Please remove armv6l. Why do you show a test for armv7l and Ming, which is Windows?

2022-04-07 17:40 UTC, alexellis requested changes
Let's reduce scope please. No arm for Windows and no armv6.

2022-04-07 17:40 UTC, alexellis commented on pkg/get/get_test.go
> +			url:     `https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-windows_armv6.zip`,
Please remove

2022-04-07 17:40 UTC, alexellis commented on pkg/get/get_test.go
> +			url:     `https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-windows_armv7.zip`,
Please remove

2022-04-07 17:40 UTC, alexellis commented on pkg/get/get_test.go
> +			url:     `https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-windows_arm64.zip`,
We have no windows arm files so let's remove. Less is more

2022-04-08 06:45 UTC, Shikachuu commented
> Please remove armv6l. Why do you show a test for armv7l and Ming, which is Windows?

[Because somehow they've got binaries for that.](https://github.com/junegunn/fzf/releases/tag/0.30.0)
But if you wish I can remove armv6l from every os and remove every windows version except arm64 and amd64.

2022-04-08 06:46 UTC, alexellis commented
Thank you, please go ahead for this new CLI. We don't need to maintain things that people can't or won't use.

2022-04-09 07:28 UTC, alexellis commented on pkg/get/get_test.go
> +			url:     `https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-linux_armv6.tar.gz`,
Let's just keep armv7 and arm64 please

2022-04-10 19:38 UTC, Shikachuu commented on pkg/get/get_test.go
> +			url:     `https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-linux_armv6.tar.gz`,
Done!

2022-04-10 19:38 UTC, Shikachuu commented
> Please see comments

Done :heavy_check_mark:

2022-06-29 11:02 UTC, alexellis commented
This PR needs to be rebased before we can merge it.

2022-06-29 11:10 UTC, closed without merging